#!/usr/bin/env python 

import roslib; roslib.load_manifest('hid')

import rospy
from hid.msg import Controller360State
from turtlesim.msg import Velocity

def callback(data,pub):
  v= Velocity()
  v.linear = data.left_joy_y/32000.0
  v.angular = -1*data.left_joy_x/32000.0
  pub.publish(v)
  rospy.loginfo(rospy.get_name() + ": Received command")


rospy.init_node('turtlesim_control',anonymous=True)
pub = rospy.Publisher('turtle1/command_velocity',Velocity)
rospy.Subscriber("xbox_360/controller_360_state", Controller360State, callback,                 pub)
rospy.spin()
